# ------------------- Dashboard Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: eureka-manage
  name: eureka-manage
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: eureka-manage
#  template:
#    metadata:
#      labels:
#        k8s-app: kubernetes-dashboard
    spec:
      containers:
      - name: eureka-manage
        image: 172.26.206.220/library/eureka-manage-ui:1.0.0
        ports:
        - containerPort: 3001
          protocol: TCP
#        args:
#          - --auto-generate-certificates
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
#        volumeMounts:
#        - name: kubernetes-dashboard-certs
#          mountPath: /certs
#          # Create on-disk volume to store exec logs
#        - mountPath: /tmp
#          name: tmp-volume
#        livenessProbe:
#          httpGet:
#            scheme: HTTPS
#            path: /
#            port: 8443
#          initialDelaySeconds: 30
#          timeoutSeconds: 30
#      volumes:
#      - name: kubernetes-dashboard-certs
#        secret:
#          secretName: kubernetes-dashboard-certs
#      - name: tmp-volume
#        emptyDir: {}
#      serviceAccountName: kubernetes-dashboard
#      # Comment the following tolerations if Dashboard must not be deployed on master
#      tolerations:
#      - key: node-role.kubernetes.io/master
#        effect: NoSchedule
